<?php declare(strict_types = 1);

namespace Tp\Exceptions;

/**
 * Base class for all exceptions generated by ThePay component.
 */
class Exception extends \Exception
{

	public $defaultMessage = 'Generic ThePay exception';

	public function __construct(?string $message = null)
	{
		if ($message === null) {
			parent::__construct($this->defaultMessage);
		} else {
			parent::__construct($message);
		}
	}

}
