<?php
declare(strict_types=1);

namespace Tp;

/**
 * Base class for all exceptions generated by ThePay component.
 */
class Exception extends \Exception
{
	public $defaultMessage = 'Generic ThePay exception';

	function __construct(string $message = NULL)
	{
		if (is_null($message)) {
			parent::__construct($this->defaultMessage);
		}
		else {
			parent::__construct($message);
		}
	}
}
